version: "3"
services:
    nextjs:
        build: ./
        ports:
            - 3000:3000
    oauth:
        build: ./netlifycms-oauth
        ports:
            - 3001:3001
        env_file:
            ./netlifycms-oauth/.env
    nginx:
        build: ./nginx
        ports:
          - 80:80
        depends_on:
            - nextjs
            - oauth