backend:
  name: github
  branch: poc
  repo: prprafful/stayq_website
  base_url: https://www-staging.stayqrious.net
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - file: "content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Meta"
            name: "meta"
            widget: "object"
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: og:locale, name: og_locale, widget: string }
              - { label: og:type, name: og_type, widget: string }
              - { label: og:title, name: og_title, widget: string }
              - { label: og:description, name: og_description, widget: string }
              - { label: og:url, name: og_url, widget: string }
              - { label: og:site_name, name: og_site_name, widget: string }
              - { label: og:image, name: og_image, widget: string }
              - { label: og:image_width, name: og_image_width, widget: string }
              - {
                  label: og:image_height,
                  name: og_image_height,
                  widget: string,
                }
              - {
                  label: og:twitter_card,
                  name: og_twitter_card,
                  widget: string,
                }
              - { label: og:label1, name: og_label1, widget: string }
              - { label: og:data1, name: og_data1, widget: string }
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Button Text, name: button, widget: string }
              - { label: Banner Image, name: banner_img, widget: string }
          - label: "Features"
            name: "features"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Feature list"
                name: "feature_list"
                widget: "list"
                max: 4
                fields:
                  - { label: Image, name: image, widget: string }
                  - { label: Title, name: title, widget: string }

      - file: "content/curriculum.md"
        label: "Curriculum Page"
        name: "curriculum"
        fields:
          - label: "Meta"
            name: "meta"
            widget: "object"
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: og:locale, name: og_locale, widget: string }
              - { label: og:type, name: og_type, widget: string }
              - { label: og:title, name: og_title, widget: string }
              - { label: og:description, name: og_description, widget: string }
              - { label: og:url, name: og_url, widget: string }
              - { label: og:site_name, name: og_site_name, widget: string }
              - { label: og:image, name: og_image, widget: string }
              - { label: og:image_width, name: og_image_width, widget: string }
              - {
                  label: og:image_height,
                  name: og_image_height,
                  widget: string,
                }
              - {
                  label: og:twitter_card,
                  name: og_twitter_card,
                  widget: string,
                }
              - { label: og:label1, name: og_label1, widget: string }
              - { label: og:data1, name: og_data1, widget: string }
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subtitle, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Button Text, name: button, widget: string }
              - { label: Banner Color, name: banner_color, widget: string }
          - label: "Courses Outcome"
            name: "courses_outcome"
            widget: "object"
            fields:
              - { label: Title, name: title, widget: string }
              - label: "Outcome list"
                name: "outcomes_list"
                widget: "list"
                max: 10
                fields:
                  - { label: Title, name: title, widget: string }

  - name: "curriculums"
    label: "Curriculums"
    create: true
    folder: content/curriculums
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - label: "Header"
        name: "header"
        widget: "object"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subtitle, widget: string }
          - { label: Description, name: description, widget: markdown }
          - { label: Button Text, name: button, widget: string }
          - { label: Banner Color, name: banner_color, widget: string }
          
      - label: "Meta"
        name: "meta"
        widget: "object"
        collapsed: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: og:locale, name: og_locale, widget: string, required: false }
          - { label: og:type, name: og_type, widget: string, required: false }
          - { label: og:title, name: og_title, widget: string, required: false }
          - { label: og:description, name: og_description, widget: string, required: false }
          - { label: og:url, name: og_url, widget: string, required: false }
          - { label: og:site_name, name: og_site_name, widget: string, required: false }
          - { label: og:image, name: og_image, widget: string, required: false }
          - { label: og:image_width, name: og_image_width, widget: string, required: false }
          - {
              label: og:image_height,
              name: og_image_height,
              widget: string,
              required: false,
            }
          - {
              label: og:twitter_card,
              name: og_twitter_card,
              widget: string,
              required: false
            }
          - { label: og:label1, name: og_label1, widget: string, required: false }
          - { label: og:data1, name: og_data1, widget: string, required: false }
